<a href="https://colab.research.google.com/github/Divya28092005/Data_Science_Lab/blob/main/ds3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a) Create a 3×3 Matrix and Compute its Determinant (User Input)

In [2]:
import numpy as np

print("Enter elements of 3x3 matrix:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1} elements separated by space: ").split()))
    matrix.append(row)

matrix = np.array(matrix)

print("Original 3x3 matrix:")
print(matrix)

determinant = np.linalg.det(matrix)

print("\nDeterminant of the matrix:", determinant)

Enter elements of 3x3 matrix:
Enter row 1 elements separated by space: 7 4 1 
Enter row 2 elements separated by space: 2 5 8 
Enter row 3 elements separated by space: 9 3 6
Original 3x3 matrix:
[[7 4 1]
 [2 5 8]
 [9 3 6]]

Determinant of the matrix: 242.99999999999994


b) Find the Inverse of the Matrix (User Input)

In [3]:
import numpy as np

print("Enter elements of 3x3 matrix:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1} elements separated by space: ").split()))
    matrix.append(row)

matrix = np.array(matrix)

print("Matrix:")
print(matrix)

det = np.linalg.det(matrix)

print("\nDeterminant:", det)

if det != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("\nMatrix is singular, inverse does not exist.")

Enter elements of 3x3 matrix:
Enter row 1 elements separated by space: 2 5 1 
Enter row 2 elements separated by space: 3 1 2
Enter row 3 elements separated by space: 1 2 1
Matrix:
[[2 5 1]
 [3 1 2]
 [1 2 1]]

Determinant: -6.0

Inverse of the matrix:
[[ 0.5         0.5        -1.5       ]
 [ 0.16666667 -0.16666667  0.16666667]
 [-0.83333333 -0.16666667  2.16666667]]


c) Solve Linear Equations using NumPy (User Input)

In [4]:
import numpy as np

print("Enter coefficients for equation 1 (a b):")
a1, b1 = map(int, input().split())

print("Enter coefficients for equation 2 (a b):")
a2, b2 = map(int, input().split())

print("Enter constants for equations:")
c1, c2 = map(int, input().split())

A = np.array([[a1, b1],
              [a2, b2]])

B = np.array([c1, c2])

print("Coefficient Matrix A:")
print(A)

print("\nConstants Vector B:")
print(B)

solution = np.linalg.solve(A, B)

print("\nSolution for [x, y]:")
print(solution)

Enter coefficients for equation 1 (a b):
2 3
Enter coefficients for equation 2 (a b):
4 5
Enter constants for equations:
10 20
Coefficient Matrix A:
[[2 3]
 [4 5]]

Constants Vector B:
[10 20]

Solution for [x, y]:
[5. 0.]
