<a href="https://colab.research.google.com/github/Divya28092005/Data_Science_Lab/blob/main/Ex_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#####Using NumPy Library implement the following problem statements:


#####a) Create a 3x3 square matrix and compute its determinant.

In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original 3x3 matrix:")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("\nDeterminant of the matrix:", determinant)

Original 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0



######b) Find the inverse of the matrix

In [4]:
import numpy as np

# Create a new non-singular 3x3 matrix
# This matrix is chosen to be invertible (non-singular)
non_singular_matrix = np.array([
    [2, 5, 1],
    [3, 1, 2],
    [1, 2, 1]
])

print("New Non-singular 3x3 matrix:")
print(non_singular_matrix)

# Compute the determinant of the new matrix to confirm it's non-singular
non_singular_determinant = np.linalg.det(non_singular_matrix)
print("\nDeterminant of the non-singular matrix:", non_singular_determinant)

# Since the determinant is non-zero, we can compute its inverse
if not np.isclose(non_singular_determinant, 0):
    inverse_non_singular_matrix = np.linalg.inv(non_singular_matrix)
    print("\nInverse of the non-singular matrix:")
    print(inverse_non_singular_matrix)
else:
    print("\nError: The new matrix is also singular, which should not happen with this example.")

New Non-singular 3x3 matrix:
[[2 5 1]
 [3 1 2]
 [1 2 1]]

Determinant of the non-singular matrix: -6.0

Inverse of the non-singular matrix:
[[ 0.5         0.5        -1.5       ]
 [ 0.16666667 -0.16666667  0.16666667]
 [-0.83333333 -0.16666667  2.16666667]]


#####c) Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20


In [6]:
import numpy as np

# c) Solve the following system of linear equations using NumPy:
#    2x + 3y = 10
#    4x + 5y = 20

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constants vector B
B = np.array([10, 20])

print("Coefficient Matrix A:")
print(A)
print("\nConstants Vector B:")
print(B)

# Solve the system of linear equations
# This function computes the 'exact' solution, x, to the equation Ax = B.
x_solution = np.linalg.solve(A, B)

print("\nSolution for [x, y]:")
print(x_solution)

# Verify the solution by plugging x and y back into the original equations
print("\nVerification:")
print(f"2*{x_solution[0]:.2f} + 3*{x_solution[1]:.2f} = {2*x_solution[0] + 3*x_solution[1]:.2f} (expected 10)")
print(f"4*{x_solution[0]:.2f} + 5*{x_solution[1]:.2f} = {4*x_solution[0] + 5*x_solution[1]:.2f} (expected 20)")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constants Vector B:
[10 20]

Solution for [x, y]:
[5. 0.]

Verification:
2*5.00 + 3*0.00 = 10.00 (expected 10)
4*5.00 + 5*0.00 = 20.00 (expected 20)
